@host = localhost:8080
@token = super-secret-token

### Testar se o servidor está de boas
GET /health HTTP/1.1
Host: {{host}}
Accept: text/plain
Authorization: Bearer {{token}}

### New dev
POST /api/v1/desenvolvedor HTTP/1.1
Host: {{host}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "dev"
}
